NOMURA_STOCK_EMAIL=""
NOMURA_STOCK_PASS=""
MONEY_TREE_EMAIL=""
MONEY_TREE_PASS=""
export NOMURA_STOCK_EMAIL NOMURA_STOCK_PASS MONEY_TREE_EMAIL MONEY_TREE_PASS

python3 motikab_info.py

unset NOMURA_STOCK_EMAIL NOMURA_STOCK_PASS MONEY_TREE_EMAIL MONEY_TREE_PASS



